package:
  name: utils
  version: !!str 0.7

source:
  fn: utils-0.7.tar.gz
  url: https://pypi.python.org/packages/source/u/utils/utils-0.7.tar.gz
  md5: 9b454a7775735ff7939cca269bf89067
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - utils = utils:main
    #
    # Would create an entry point called utils that calls utils.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - tests
    - tests.dicts
    - utils
    - utils.dicts

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/haaksmash/pyutils
  license: UNKNOWN
  summary: 'Python Distribution Utilities'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
